#!/usr/bin/env node
/**
 * Download MLB Team Logos
 *
 * Fetches official team logos from MLB Stats API and saves them locally
 * Generates TypeScript mapping file for easy access
 *
 * Usage: node scripts/download-logos.js
 */

import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const BASE_URL = 'https://statsapi.mlb.com/api/v1';
const LOGOS_DIR = path.join(__dirname, '../frontend/public/logos/mlb');
const MAPPING_FILE = path.join(__dirname, '../frontend/src/lib/constants/logos.ts');

// MLB team IDs (all 30 teams)
const MLB_TEAM_IDS = [
  108, // LAA - Los Angeles Angels
  109, // ARI - Arizona Diamondbacks
  110, // BAL - Baltimore Orioles
  111, // BOS - Boston Red Sox
  112, // CHC - Chicago Cubs
  113, // CIN - Cincinnati Reds
  114, // CLE - Cleveland Guardians
  115, // COL - Colorado Rockies
  116, // DET - Detroit Tigers
  117, // HOU - Houston Astros
  118, // KCR - Kansas City Royals
  119, // LAD - Los Angeles Dodgers
  120, // WSH - Washington Nationals
  121, // NYM - New York Mets
  133, // OAK - Oakland Athletics
  134, // PIT - Pittsburgh Pirates
  135, // SDP - San Diego Padres
  136, // SEA - Seattle Mariners
  137, // SFG - San Francisco Giants
  138, // STL - St. Louis Cardinals
  139, // TBR - Tampa Bay Rays
  140, // TEX - Texas Rangers
  141, // TOR - Toronto Blue Jays
  142, // MIN - Minnesota Twins
  143, // PHI - Philadelphia Phillies
  144, // ATL - Atlanta Braves
  145, // CWS - Chicago White Sox
  146, // MIA - Miami Marlins
  147, // NYY - New York Yankees
  158, // MIL - Milwaukee Brewers
];

/**
 * Fetch team data from MLB Stats API
 */
async function fetchTeamData(teamId) {
  const url = `${BASE_URL}/teams/${teamId}`;

  try {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }

    const data = await response.json();
    const team = data.teams[0];

    return {
      id: team.id,
      name: team.name,
      abbreviation: team.abbreviation,
      teamName: team.teamName,
      locationName: team.locationName,
    };
  } catch (error) {
    console.error(`❌ Error fetching team ${teamId}:`, error.message);
    return null;
  }
}

/**
 * Download logo from MLB.com
 * Multiple logo formats available:
 * - Cap logo: https://www.mlbstatic.com/team-logos/{teamId}.svg
 * - Primary logo: https://www.mlbstatic.com/team-logos/team-primary-logo/{teamId}.svg
 */
async function downloadLogo(teamId, abbreviation) {
  // Try cap logo first (simpler, more recognizable)
  const logoUrl = `https://www.mlbstatic.com/team-logos/${teamId}.svg`;

  try {
    const response = await fetch(logoUrl);
    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }

    const svgContent = await response.text();
    const filename = `${abbreviation.toLowerCase()}.svg`;
    const filepath = path.join(LOGOS_DIR, filename);

    await fs.writeFile(filepath, svgContent, 'utf-8');
    console.log(`✅ Downloaded: ${abbreviation} (${teamId})`);

    return { teamId, abbreviation, filename };
  } catch (error) {
    console.error(`❌ Failed to download logo for ${abbreviation} (${teamId}):`, error.message);
    return null;
  }
}

/**
 * Generate TypeScript mapping file
 */
function generateMappingFile(logos) {
  const content = `/**
 * MLB Team Logos Mapping
 * Auto-generated by scripts/download-logos.js
 * Last updated: ${new Date().toISOString()}
 */

export const MLB_LOGOS: Record<number, string> = {
${logos.map(logo => `  ${logo.teamId}: '/logos/mlb/${logo.filename}', // ${logo.abbreviation}`).join('\n')}
};

export const MLB_LOGOS_BY_ABBR: Record<string, string> = {
${logos.map(logo => `  '${logo.abbreviation}': '/logos/mlb/${logo.filename}',`).join('\n')}
};

/**
 * Get logo path for team
 */
export function getMLBLogo(teamIdOrAbbr: number | string): string {
  if (typeof teamIdOrAbbr === 'number') {
    return MLB_LOGOS[teamIdOrAbbr] || '/logos/mlb/default.svg';
  }
  return MLB_LOGOS_BY_ABBR[teamIdOrAbbr] || '/logos/mlb/default.svg';
}
`;

  return content;
}

/**
 * Main execution
 */
async function main() {
  console.log('🚀 Starting MLB logos download...\n');

  // Create logos directory
  try {
    await fs.mkdir(LOGOS_DIR, { recursive: true });
    console.log(`📁 Created directory: ${LOGOS_DIR}\n`);
  } catch (error) {
    console.error('❌ Failed to create directory:', error.message);
    process.exit(1);
  }

  // Fetch team data and download logos
  const results = [];

  for (const teamId of MLB_TEAM_IDS) {
    // Fetch team metadata
    const teamData = await fetchTeamData(teamId);
    if (!teamData) continue;

    // Download logo
    const result = await downloadLogo(teamId, teamData.abbreviation);
    if (result) {
      results.push(result);
    }

    // Rate limiting: 200ms delay between requests
    await new Promise(resolve => setTimeout(resolve, 200));
  }

  console.log(`\n✅ Downloaded ${results.length}/${MLB_TEAM_IDS.length} logos\n`);

  // Generate TypeScript mapping
  if (results.length > 0) {
    try {
      // Create constants directory
      const constantsDir = path.dirname(MAPPING_FILE);
      await fs.mkdir(constantsDir, { recursive: true });

      const mappingContent = generateMappingFile(results);
      await fs.writeFile(MAPPING_FILE, mappingContent, 'utf-8');

      console.log(`✅ Generated mapping file: ${MAPPING_FILE}`);
      console.log(`\n📦 Logos ready to use with:`);
      console.log(`   import { getMLBLogo } from '@lib/constants/logos';`);
      console.log(`   const logoPath = getMLBLogo(119); // LAD`);
      console.log(`   const logoPath = getMLBLogo('LAD');`);
    } catch (error) {
      console.error('❌ Failed to generate mapping file:', error.message);
      process.exit(1);
    }
  }

  console.log('\n✨ Done!\n');
}

// Run
main().catch(error => {
  console.error('💥 Fatal error:', error);
  process.exit(1);
});
